sudo: required
services:
     - docker
script:
     - docker build -t laye195/node:nodedemo .
     - docker images  laye195/node 

before_deploy:
      - docker login  -u laye195 -p Mathematique

deploy:
   provider: script
   script: docker push laye195/node:nodedemo
   on:
      branch: master               
