sudo: required
services:
     - docker
script:
     - docker build -t laye/node .
     - docker images  laye/node 

before_deploy:
      - docker login  -u laye195 -p Mathematique

deploy:
   provider: script
   script: docker push laye195/nodeproject
   on:
      branch: master               